# Generated by Django 3.0.5 on 2021-07-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='admitDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateTimeField(),
        ),
    ]
